### ISSUE TITLE
本文和KDD 2020的MTGNN相似度很高，文中称自己提出是否不恰当？

### ISSUE THREAD

**Issue by SmILeel** [nuist-cs/MS-STGNN#1]

**Comment by nuist-cs** [comment]
这个确实是引用了MTGNN的主体框架（我在文中也引用了MTGNN论文），我们提出了新的图学习模块更好的学习了邻接矩阵，变量注意力模块去增加鲁棒性。




现实&nbsp;改变了我们。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nuist-cs/MS-STGNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月22日(星期五) 中午1:13
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [nuist-cs/MS-STGNN] 这你确定不是给KDD 2020的 MTGNN套壳吗？   (Issue #1)





 
Closed #1 as completed.

**Comment by SmILeel** [comment]
这个引用也相当隐蔽，该引TCN的地方来提MTGNN，表现地只有子模块是相同的。

**Comment by nuist-cs** [comment]
本文的创新点就是提出图学习模块和注意力机制。在TCN部分我们明确引用了MTGNNMulti-scale temporal convolution module: We use onedimensional
dilation convolution filters at multiple scales to implement our multi-scale temporal convolution module [21].




现实&nbsp;改变了我们。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nuist-cs/MS-STGNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月22日(星期五) 中午1:42
***@***.***&gt;;
抄送:&nbsp;"现实 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [nuist-cs/MS-STGNN] 本文和KDD 2020的MTGNN相似度很高，文中称自己提出是否不恰当？ (Issue #1)





 
这个引用也相当隐蔽，该引TCN的地方来提MTGNN，表现地只有子模块是相同的。

**Comment by SmILeel** [comment]
并没有别的意思，但是你这个地方该引用的论文是TCN，你可以去看看TCN的论文，图都跟你这个一样
![image](https://github.com/nuist-cs/MS-STGNN/assets/107383023/a3d23c3a-1080-4fdc-ae29-c36d4f28fdb6)
而对本文整体框架几乎完全套用MTGNN，几乎是一点没体现，这并不规范。

**Comment by nuist-cs** [comment]
我也非常感谢您提出的疑问。TCN只是MTGNN中多尺度的一部分，MTGNN是在TCN的基础上进一步提出了多尺度TCN。整体框架是完全套用MTGNN，但是我们在MTGNN的基础上进行了改进。包括WaveForM: Graph Enhanced Wavelet Learning for Long Sequence Forecasting of Multivariate Time Series, published in AAAI 2023.也是在MTGNN的基础上改进。
&nbsp;


现实&nbsp;改变了我们。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月22日(星期五) 中午1:52
收件人: ***@***.***&gt;; 
抄送: "现实 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nuist-cs/MS-STGNN] 本文和KDD 2020的MTGNN相似度很高，文中称自己提出是否不恰当？ (Issue #1)





 
并没有别的意思，但是你这个地方该引用的论文是TCN，你可以去看看TCN的论文，图都跟你这个一样
 
 而对本文整体框架几乎完全套用MTGNN，几乎是一点没体现，这并不规范。

**Comment by SmILeel** [comment]
可以理解。那篇文章被引一千多次，根据它改的论文很多，但是你这个问题在于文中框架图等都和原论文过于相似甚至一模一样了，至少应该换个表现方法，另外就是并没有直接去提和原论文的关系，这并不好，让真正了解该领域的人一看会显得过于简单且相似了。

**Comment by nuist-cs** [comment]
我并不是在和你辩论，我只是想请教一下您。我应该怎么去引用MTGNN，或者说怎么去换个表现方法，方便我下面写论文。你说的确实是这样过于简单，我的图学习模块和注意力机制我是花了很多功夫和时间想出来的，你在这说过于简单了，我真的不知道该怎么回答你。现在的顶会论文大家都在用transformer结构，改进注意力机制。我也不知道下面一篇该怎么写了。希望您能指导一下。




现实&nbsp;改变了我们。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nuist-cs/MS-STGNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月22日(星期五) 下午2:10
***@***.***&gt;;
抄送:&nbsp;"现实 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [nuist-cs/MS-STGNN] 本文和KDD 2020的MTGNN相似度很高，文中称自己提出是否不恰当？ (Issue #1)





 
可以理解。那篇文章被引一千多次，根据它改的论文很多，但是你这个问题在于文中框架图等都和原论文过于相似甚至一模一样了，至少应该换个表现方法，另外就是并没有直接去提和原论文的关系，这并不好，让真正了解该领域的人一看会显得过于简单且相似了。

**Comment by SmILeel** [comment]
可以明确提出我们基于xx做了xx修改。
这是IJCAI2019的GraphWaveNet（MTGNN同作者）
![image](https://github.com/nuist-cs/MS-STGNN/assets/107383023/af0ded55-8731-486a-b9ef-de2a9fac14ee)
这是MTGNN的graph convolution
![image](https://github.com/nuist-cs/MS-STGNN/assets/107383023/c6592bbe-47ac-4120-ae6e-d1145aab5224)
这是你的框架
![image](https://github.com/nuist-cs/MS-STGNN/assets/107383023/c2e607f4-24be-4759-8655-547e4e65f4d3)
另外这个IJCAI的论文你甚至并没有引用。

**Comment by nuist-cs** [comment]
我还想请教一下，我下一篇用的Transformer模型，那我这个结构是不是不能用？我看大家都是这个结构。我相信大家关注点是这篇论文对自己有没有用去看，而不是盯着图片结构。




现实&nbsp;改变了我们。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nuist-cs/MS-STGNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月22日(星期五) 下午2:45
***@***.***&gt;;
抄送:&nbsp;"现实 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [nuist-cs/MS-STGNN] 本文和KDD 2020的MTGNN相似度很高，文中称自己提出是否不恰当？ (Issue #1)





 
可以明确提出我们基于xx做了xx修改。
 这是IJCAI2019的GraphWaveNet（MTGNN同作者）
 
 这是MTGNN的graph convolution
 
 这是你的框架
 
 另外这个IJCAI的论文你甚至并没有引用。

**Comment by SmILeel** [comment]
good luck，能说服自己就可以。
