### ISSUE TITLE
想请教一下日期特征怎么处理

### ISSUE THREAD

**Issue by 1229308805** [nuist-cs/MS-STGNN#2]
老师您好，我有一个疑问：日历数据 比如是否为节假日和周末(1/0)，这个特征模型是如何使用的呢，是和其他历史数据一样作为图的一个节点吗？

**Comment by nuist-cs** [comment]
对的，每个变量均作为图的一个节点。&nbsp;


现实&nbsp;改变了我们。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月29日(星期天) 下午4:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [nuist-cs/MS-STGNN] 想请教一下日期特征怎么处理 (Issue #2)














 
老师您好，我有一个疑问：日历数据 比如是否为节假日和周末(1/0)，这个特征模型是如何使用的呢，是和其他历史数据一样作为图的一个节点吗？

**Comment by 1229308805** [comment]
谢谢您的快速解答
