### ISSUE TITLE
有关注意力机制层

### ISSUE THREAD

**Issue by qa1234561** [nuist-cs/MS-STGNN#4]
您好，在您的文章中所提到的FA层的使用，在您的代码中设置了自注意力机制层与空间注意力机制层，但是在您的模型中似乎并没有用到自注意力机制层，只是把空间注意力层添加到了FA层，请问这样有什么深意么？

**Comment by nuist-cs** [comment]
感谢您对我们论文的关注。我们在代码中并没有使用自注意力机制层。可能是我们的命名方式引起了您的误解，对此我们深感抱歉。
